# Generated by Django 4.1 on 2022-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domain', models.CharField(max_length=50)),
                ('Votes', models.CharField(max_length=50)),
                ('Dates', models.CharField(max_length=50)),
                ('Links', models.CharField(max_length=50)),
                ('wage', models.FloatField()),
            ],
        ),
    ]
